5. Flex page grids
htmlacademy-htmlcss/2450769-sedona-1 pull request #5
Opened 2024-01-18 10:11 UTC by AndeyAK

2024-01-18 18:37 UTC, firefoxic requested changes

2024-01-18 18:37 UTC, firefoxic commented on index.html
> +
Может тогда отдельным пунктом списка?

2024-01-18 18:37 UTC, firefoxic commented on index.html
> +            <li>
А тут наоборот фото теперь не относится к тексту. Ради стилизации не стоит так делать.

2024-01-18 18:37 UTC, firefoxic commented on index.html
> +              <img class="advantages-img" src="images/stone.jpg" alt="Каньен и горы" width="800" height="385">
И тут фотка оторвалась 😕

2024-01-18 18:37 UTC, firefoxic commented on catalog.html
> +              <button class="button-favourite" type="button">В избранное</button>
Фото товара (в нашем случае отеля) тоже является информацией о нём, и заголовок должен быть перед озаглавливаемым контентом. Стилями мы можем поменять порядок.

2024-01-18 18:37 UTC, firefoxic commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
Много где добавляешь `font-family`. Но в этом нет необходимости. Ведь шрифт и так по всему проекте _PT Sans_. Достаточно один раз его указать на `html` или `body`. А в элементах, которые не наследуют шрифт (поля ввода, кнопки и тд) просто прописать этому свойству `inherit`. Это позволит например при смене шрифта в проекте поменять его лишь в одном месте.

2024-01-18 18:37 UTC, firefoxic commented on styles/styles.css
> +  margin: 0 auto;
В современных дизайнах, где всегда что-то тянется до краёв вьюпорта, это правильный подход — указывать ширину и авто-отступы на каждой секции. На втором курсе так и будем делать.

Но тут макет такой, что мало того что нет тянущихся до краёв фонов, так ещё и есть тень общая от всего столбца контента. И вот эту тень не получится добавить каждой секции — это приведёт к тому, что тень будет накладываться на предыдущую секцию, а нам надо, чтобы она была только с боков.

В общем с таким дизайном выход только такой: всё содержимое `body` оборачиваем в контейнер и ему задаём фиксированную ширину и авто-отступы (на него же потом и тень повесим), а с секций это всё убираем. Либо можно ещё самому `body` задать ширину и отступы, чтобы он был тем самым контейнером, но некоторые проверяющие как огня боятся таких манипуляций с `body`.

2024-01-21 12:26 UTC, AndeyAK commented on index.html
> +
Исправил!

2024-01-21 12:33 UTC, AndeyAK commented on index.html
> +            <li>
Тут убрал фото как отдельный элемент списка

2024-01-21 12:33 UTC, AndeyAK commented on index.html
> +              <img class="advantages-img" src="images/stone.jpg" alt="Каньен и горы" width="800" height="385">
+

2024-01-21 12:50 UTC, AndeyAK commented on catalog.html
> +              <button class="button-favourite" type="button">В избранное</button>
убрал картинку с первой позиции и стилями поднял наверх

2024-01-21 12:52 UTC, AndeyAK commented on styles/styles.css
> +  font-family: "PT Sans", sans-serif;
Исправил

2024-01-21 13:03 UTC, AndeyAK commented on styles/styles.css
> +  margin: 0 auto;
Исправил

2024-01-21 17:33 UTC, merged